[workflow]
workflow_readme = ["readme"]
workflow_workflow_yml = ["workflow_yml"]
workflow_support =  ["readme", "workflow_yml"]
workflow_all = ["all"]

[group.readme]
examples = ['README.md']
patterns = ['^README.md$']

[group.workflow_yml]
examples = [".github/workflows/check.yml", ".github/workflows/run_on_push.yml"]
patterns = ['^\.github/workflows/.*\.yml$']


[group.all]
examples = ["check_file_changed/config.toml"]
patterns = ['.*']
