name: Test and lint
on:
  push:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'requirements-ci.txt'
      - 'requirements-dev.txt'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - uses: pre-commit/action@v3.0.0
      - name: Install
        run: |
          pip install -q .
      - name: Test with pytest
        run: |
          pytest -v --cov=check_file_changed._file_checker
